### ISSUE TITLE
[Custom inputBarView] Photo button icon weird behaviour

### ISSUE THREAD

**Issue by AndreMarvell** [eBay/NMessenger#100]
Hi,

I'm using custom inputbar in my app, but for some reason i can't explain, the photo button icon is sometimes duplicated and moved in the top of the screen like below.

![img_1741](https://cloud.githubusercontent.com/assets/5513545/23834752/e5272dde-075b-11e7-939d-cabb952136c5.PNG)

I've you ever encoutered this issue ?

Thank you,

**Comment by AndreMarvell** [comment]
@atainter Do you have an idea for my issue. Thank you.

**Comment by atainter** [comment]
Nice app.

You created this input bar? It shouldn't do this since we only reference the view. How do you create the view? Do you use the `getInputBar` method?

**Comment by AndreMarvell** [comment]
Thank you :-).

Yes i do. I do use getInputBar in my extended NMessengerController.
I created my custom inpubar by extending InputBarView and its xib as specified in the documentation.

I have an archive with the two file (custom inputbar and xib), maybe when you'll have time, you could check what's wrong with my implementation.
[Livetalk.zip](https://github.com/eBay/NMessenger/files/874968/Livetalk.zip)

NB : When i disable the button, i do not reproduce the problem.

Thank you for your time and above all for this awesome library

**Comment by AndreMarvell** [comment]
Hi, @atainter did you have time to check my issue?

Thank you,

**Comment by AndreMarvell** [comment]
Hi, @atainter, this ticket can be closed. I solved the issue by editing the input bar constraints.

Thank you
