### ISSUE TITLE
[CollectionViewWithNodes] How to define cell width? 

### ISSUE THREAD

**Issue by alexandremorgado** [eBay/NMessenger#101]
I'm creating a chat with custom nodes that can be added to collection views. So I'm using **createCollectionNodeMessage** function, that returns a GeneralMessengerCell with nodes inside. 

But GeneralMessengerCell don't fills available screen width, like sample on Readme. Insted, cell gets about only 60% of screen. like this 👇 

![screen shot 2017-03-16 at 09 08 19](https://cloud.githubusercontent.com/assets/868934/23995731/8ba08992-0a29-11e7-9229-3fd9dc727bc0.png)
 
This collection node is added to a MessageGroup, so maybe group is limiting width. I've tried override layoutSpecThatFits in some classes, but without success on setting width. 

I'm using NMessenger 1.0.80 (ASDK-2.1 branch). 

So, how can I define a larger width for collections? 

PS: Thank you for this great library!

**Comment by alexandremorgado** [comment]
I found out where is the problem. Is not in MessageGroup. The place where the node width is being shorten is on layoutSpecThatFits from MessageNode:   

`contentNode?.style.maxWidth = ASDimension(unit: .points, value: width * (2/3))`

Now I need to find a way to set a larger maxWidth only when messegeCell is a collection node message. Any ideias?

**Comment by alexandremorgado** [comment]
I got it! **createCollectionNodeMessage()** embed a CollectionViewContentNode into a new MessageNode, that change width to 2/3 of size. So I inserted nodes directly on CollectionViewContentNode and voilà, no more MessageNode resizing message.

**Comment by alexandremorgado** [comment]
This issue can be closed :-) 

I just let a suggestion for that be possible to set this maxWidth on contentNode. 

Thanks.

**Comment by atainter** [comment]
I'll make the change. Let me take a note of it. Thanks for documenting this!

**Comment by atainter** [comment]
Updated in master.

**Comment by Cramsden** [comment]
@atainter Now that this is updated, what is the flow for modifying the maxwidth on a content node?

**Comment by vandana26V** [comment]
Can anyone provide me the sample code to create node from view(view from xib).
