### ISSUE TITLE
Support custom input views

### ISSUE THREAD

**Issue by alibasta** [eBay/NMessenger#11]
Hi David,

to support own custom input views please move the `setUpConstriantsForViews()` method from `viewDidLoad()` to `viewWillAppear(animated: Bool)`.

After that change we are able to create our own input views in our `NMessengerViewController` by doing the following: 

```
    override func viewDidLoad() {
        super.viewDidLoad()

        self.inputBarView.removeFromSuperview()
        self.inputBarView = NuukInputBarView(controller: self)
        self.view.addSubview(self.inputBarView)
    }

```

Best Alex

**Comment by DavidSchechter** [comment]
Made pr #13

**Comment by atainter** [comment]
@alibasta Are you using the code on master or the latest cocoapod?

**Comment by alibasta** [comment]
Latest cocoa pod. The changes worked for me.

**Comment by nonameplum** [comment]
Why `var inputBarView: InputBarViewProtocol!` is `IBOutlet` anyways it is loaded using `loadInputView`. Maybe best way would be make this method public that it could be overrided by custom of the `NMessengerViewController` subclass. What do you think?

**Comment by alibasta** [comment]
Thats what I recommended as cleanest way to @DavidSchechter at Slack (making the method public). He wanted this solution.

**Comment by atainter** [comment]
We're working on refactoring this right now

**Comment by nonameplum** [comment]
I'm thinking also about this to give only needed control:

``` swift
    private func loadInputView() {
        self.inputBarView = provideInputBarView()

        if let inputBarView = self.inputBarView as? UIView {
            self.view.addSubview(inputBarView)
        }
    }

...

   public func provideInputBarView() -> InputBarView {
       return InputBarView(controller: self)
   }
```

**Comment by alibasta** [comment]
Yes. Looks good to me.

**Comment by atainter** [comment]
The inputBar protocol will be implemented by a base inputBarView class which can be subclassed. Our inputBarView will subclass this base class. We're still debating how a custom inputBar should be added in the NMessengerViewController subclass.

**Comment by atainter** [comment]
#14 Added 
```public func customInputBar() -> InputBarView
     {
         return NMessengerBarView(controller: self)
      }```

`InputBarView` Is now a base class that can used to create your own InputBar.

**Comment by nonameplum** [comment]
Great 👍  For me only name of the method should be changed to fit swift naming conventions. Func should do something. Or it could be changed to computed property like:

``` swift
public var customInputBar: InputBarView {
    return return NMessengerBarView(controller: self)
}

**Comment by alibasta** [comment]
👍

**Comment by atainter** [comment]
@nonameplum We don't want to use a computed property because the inputBar will most likely only need to be created during `viewDidLoad`. However, we could update the view when this property is set. I would need to think about the repercussions of refactoring before we start implementing it. 

In regard to the function naming -- I think that we should name it something similar to `getBubble()` in `BubbleConfigurationProtocol` for consistency. Perhaps `getInputBar()`.

**Comment by nonameplum** [comment]
yeah, I agree with you. I still fell as you that method is better choice in this case.
If you started with `get` convection it sounds correct.
I can only link here swift api naming guidelines:
https://swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage

This method is like factory method so it may have `makeInputBar()` but as I said, your proposition is still great :)

**Comment by atainter** [comment]
👍 I'm going to update the documentation later today, so I'll include it in that PR.
