### ISSUE TITLE
Custom Bubble

### ISSUE THREAD

**Issue by mariododov** [eBay/NMessenger#111]
Hi, I want to know if is possible to make a custom bubble.

I want to intert into the bubble the text, behind the text add an time (Label) and an image. 

Is posible to modify it? 
How?

Cheers.

**Comment by atainter** [comment]
If you want to create a custom bubble, I would have a look at this: https://github.com/eBay/NMessenger#message-bubbles You have to subclass `bubble` and draw your own shape (or use a 9 patch image).

If you want to put custom content in the bubble, you should make your own ContentNode: https://github.com/eBay/NMessenger#content-nodes

**Comment by mariododov** [comment]
And did you have any example to create a custom content?
I can't do it.

**Comment by atainter** [comment]
All nodes in this directory extend `ContentNode`

**Comment by mariododov** [comment]
thanks :)
