### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by salmaanrizvi** [eBay/NMessenger#121]
Hi,

First, thanks for developing this awesome library. 

For reasons out of my control, my project can't use cocoapods. Is there a manual installation method that could be used?

Thanks!

**Comment by dodikk** [comment]
1. cocoapods has a `--no-integrate` flag. Not sure if it can be applied to individual projects.
2. You can clone the NMessenger code (using git submodule, [Carthage](https://github.com/carthage/carthage) or just committing it to your repository) and use the ["sub-project" approach](https://www.cocoanetics.com/2011/12/sub-projects-in-xcode/)

**Comment by dodikk** [comment]
> just committing it to your repository

I've used this approach since I've found myself doing some quick customization related hacks inside the code base.

**Comment by salmaanrizvi** [comment]
Adding it as a sub-project was the way to go
