### ISSUE TITLE
[Question] XMPP integration

### ISSUE THREAD

**Issue by NikKovIos** [eBay/NMessenger#157]
I just want to ask if there any people who had such an experience? If yes, could you please share it?)

**Comment by dodikk** [comment]
I'm afraid this is not a quite right place to ask. This library is protocol agnostic, so it should be possible to apply it for any source of messages.

`NMessenger` definitely lacks some "getting started" documentation but you can use the 
[readme - Better description of integration with messaging service](https://github.com/eBay/NMessenger/issues/95) thread as a start point.

P.S. The project I'm working at uses both `NMessenger` and `XMPPFramework` but it is under NDA.

**Comment by dodikk** [comment]
@atainter , please close this issue.
