### ISSUE TITLE
[question] How to move avatar vertically?

### ISSUE THREAD

**Issue by dannogo** [eBay/NMessenger#174]
Now I have this: 

![screen shot 2017-11-15 at 12 20 30 pm](https://user-images.githubusercontent.com/11019369/32831092-e27d7fea-c9ff-11e7-9727-2e6e51bed279.png)

I used code from issue #115 to place avatar on top:

`layoutSpecs = ASStackLayoutSpec(direction: .horizontal, spacing: 0, justifyContent: justifyLocation, alignItems: .start, children: cellOrientation)`

I need avatars to be near the arrows. So I need to adjust avatar's vertical position. 
How to do it?

**Comment by dannogo** [comment]
@dodikk Maybe you found out it already?

**Comment by dannogo** [comment]
`/**
     Spacing around the avatar. Defaults to UIEdgeInsetsMake(0, 0, 0, 10)
     */
    open var avatarInsets: UIEdgeInsets = UIEdgeInsetsMake(20, 0, 0, 10) {
        didSet {
            self.setNeedsLayout()
        }
    }`

**Comment by dodikk** [comment]
@dannogo , I used the insets property. I think you've found a correct one. Please close the issue if it helped you to achieve the expected render.
