### ISSUE TITLE
Change messengerView Background Color

### ISSUE THREAD

**Issue by jahid-hasan-polash** [eBay/NMessenger#178]
There are protocol functions to change the colors of bubbles but couldn't find how to change the background color of the whole messenger view. Tried changing the background color of the viewController and self.messengerView.backgroundColor but there's no effect.

**Comment by MdShahedMamun** [comment]
Issue fixed. Please pull from my repo branch swift4. 
> https://github.com/MdShahedMamun/NMessenger.git

**Comment by jahid-hasan-polash** [comment]
@MdShahedMamun Thank you very much. Works like a charm.

**Comment by dodikk** [comment]
@jahid-hasan-polash , have you tried operating the background color of the `ASTableNode` directly?

Here is a corresponding property 
https://github.com/eBay/NMessenger/blob/master/nMessenger/Source/Messenger/Components/NMessenger.swift#L60

**Comment by jahid-hasan-polash** [comment]
Thank you for your suggestion @dodikk . But  I didn't want to change files inside pod if I could change the background color through some protocol or something.

**Comment by dodikk** [comment]
@jahid-hasan-polash , the variable is `open` so you can change `the value` in your code without touching the codebase of NMessenger ("files inside pod").

**Comment by dodikk** [comment]
@MdShahedMamun , could you please share a link to your PullRequest with the missing method solving issue? So far, it is just a link to your repo. Thanks.
