### ISSUE TITLE
Unable to find a specification for `NMessenger`

### ISSUE THREAD

**Issue by EkambaramE** [eBay/NMessenger#20]
I can't able to install the Podfile.

Please find the images for references.. Thanks 

![screen shot 2016-08-22 at 4 34 15 pm](https://cloud.githubusercontent.com/assets/11871096/17852721/4a1933ec-6886-11e6-8cfc-9f72d3aa891f.png)
![screen shot 2016-08-22 at 4 34 34 pm](https://cloud.githubusercontent.com/assets/11871096/17852746/5dd15fe0-6886-11e6-98ce-5e9800cb79bd.png)

**Comment by atainter** [comment]
Did you try `pod repo update`?

**Comment by EkambaramE** [comment]
Sorry, I forget to use that one.. thanks now its working.. 💯  👍
