### ISSUE TITLE
Update cell data

### ISSUE THREAD

**Issue by toure20** [eBay/NMessenger#205]
<img width="371" alt="2018-07-19 14 50 34" src="https://user-images.githubusercontent.com/15181919/42932192-7791461e-8b63-11e8-8762-1dfe9fac23c4.png">
Could you give me an advice for updating cell data. Actually I need to update check mark icon after user received a message.

**Comment by dodikk** [comment]
@toure20 , take a look in this thread https://github.com/eBay/NMessenger/issues/156

**Comment by toure20** [comment]
@dodikk Thanks very much. Выручили)

**Comment by dodikk** [comment]
> @dodikk Thanks very much. Выручили)

@toure20 , please close your issue as long as it has been solved.
