### ISSUE TITLE
required a higher minimum deployment target error with CocoaPods

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [eBay/NMessenger#24]
Hi,

I'm trying to install this library via CocoaPods. I created an Xcode project (Xcode 7.3) and set its Deployment Target to 8.2.

Then I initialized the project by running `pod init`. Below is my `Podfile`.

```
platform :ios, '8.2'

target 'Messenger' do
  use_frameworks!

  pod 'NMessenger', '~> 1.0'

end
```

But when I run `pod install`, I get the following error.

> [!] Unable to satisfy the following requirements:
> 
> - `NMessenger (~> 1.0)` required by `Podfile`
> 
> Specs satisfying the `NMessenger (~> 1.0)` dependency were found, but they required a higher minimum deployment target.

Anything I'm missing?

**Comment by Isuru-Nanayakkara** [comment]
I took a look at your [`podspec`](https://github.com/eBay/NMessenger/blob/master/NMessenger.podspec) file and there it says the su[pported platform is iOS 9. This must be the cause of it. Soo which one should be changed? In your readme it says the library is supported iOS 8.2 upwards.

**Comment by atainter** [comment]
#22 It supports 8.2+. We need to change the `podspec` file.

**Comment by Isuru-Nanayakkara** [comment]
Awesome! Thanks.

**Comment by atainter** [comment]
#26

**Comment by DavidSchechter** [comment]
#27
