### ISSUE TITLE
No buttons in the camera view

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [eBay/NMessenger#33]
Hi,

In the camera view that opens up when you tap the button in the default input view, there are no buttons to take a photo or dismiss the view. Are we supposed to add them ourselves? If so, how?

![rsz_img_1676](https://cloud.githubusercontent.com/assets/2551877/18054600/322eb56c-6e22-11e6-959b-207696515caa.png)

**Comment by atainter** [comment]
There should be buttons. We'll fix it within the next few days.

**Comment by DavidSchechter** [comment]
Fixed in #36

**Comment by DavidSchechter** [comment]
fixed in #37
