### ISSUE TITLE
Custom nodes similar to timestamp view in README

### ISSUE THREAD

**Issue by stephensilber** [eBay/NMessenger#34]
I was curious if the current example could be updated to include a custom content node similar to the screenshot with timestamp views on the README page. If not, could someone explain how to either add a node that is the full width of the NMessengerView with no background? 

<img width="206" alt="nmessenger-overview" src="https://cloud.githubusercontent.com/assets/845497/18069425/10813d8e-6e15-11e6-8fca-a3cef7fd921f.png">

**Comment by atainter** [comment]
There is already an included class which gives you the ability to add a timestamp.

```swift
let messageTimestamp = MessageSentIndicator()
messageTimestamp.messageSentText = "NOW"        
self.addGeneralMessengeToMessenger(messageTimestamp)
```

To make custom components which are the full width of `NMessengerView`, you must subclass `GeneralMessengerCell`.

**Comment by atainter** [comment]
I added a section in the README too: https://github.com/eBay/NMessenger/blob/master/README.md#timestamps
