### ISSUE TITLE
cannot set avatar if the image is loaded from file

### ISSUE THREAD

**Issue by jun1st** [eBay/NMessenger#35]
Cannot set avatar if the image is loaded from file.

I download profile image and save it to the device, and then loaded it into `NSData`,  create `UIImage`,  set it as avatar

But got an error "cannot get relative dimension"

Only works with resource images now :(

**Comment by atainter** [comment]
Did you set `preferredFrameSize` on your `ASImageNode`?

**Comment by jun1st** [comment]
It is the problem.

It works after setting the `preferredFrameSize`. Thanks a lot

**Comment by atainter** [comment]
👍

**Comment by munsifhayat** [comment]
Value of type 'ASImageNode' has no member 'preferredFrameSize' ??

**Comment by munsifhayat** [comment]
Changed to : 

        avatar.style.preferredSize = CGSize(width: 25, height: 25)
