### ISSUE TITLE
Tapping on gallery button hides the status bar

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [eBay/NMessenger#38]
Hi,

I encountered this issue after the latest update with the improvements to the camera view. When I tap on the gallery button in the camera view and select a photo from my photo library and come back, the status bar is gone.

Let me show you.

1. Before doing anything. Status bar is there.
![rsz_img_1697](https://cloud.githubusercontent.com/assets/2551877/18121197/0d6cd3ac-6f81-11e6-89b2-000a9991683e.png)

2. Taps on the gallery button to bring up the image picker. Status bar is gone.
![rsz_1img_1698](https://cloud.githubusercontent.com/assets/2551877/18121309/92f8f5fa-6f81-11e6-9019-d38499bee02a.png)

3. Selects a photo. Returns to the chat view. Status bar is still gone.
![rsz_img_1699](https://cloud.githubusercontent.com/assets/2551877/18121320/a42e5450-6f81-11e6-807f-463b58f15134.png)

I did some Googling on this issue and found this [question](http://stackoverflow.com/q/3542350/1077789) which describes this very problem. There are some answers which worked for some and not for others. But that might give you an idea on how to fix this.

Thanks for the quick fixes and replies as always!

**Comment by DavidSchechter** [comment]
I tried reproducing your issue in a test project, but the status bat is still there when the gallery opens and after selecting an image.
Your issue could be related to the the fact the the messenger is inside a navigation controller.
Try presenting the messenger outside of a navigation controller and if the issue persists (which is the same way I tested and could not reproduce)

**Comment by Isuru-Nanayakkara** [comment]
I made a test project with and without having the Messenger controller embedded inside a navigation controller. But in both scenarios, the status bar didn't disappear. Strange. My actual which I'm using this library has a a little more complicated view heirarchy so that might be causing this. I'll look into it more and post my findings here.
