### ISSUE TITLE
CameraViewController capture button takes photo but does not dismiss right away

### ISSUE THREAD

**Issue by stephensilber** [eBay/NMessenger#41]
When using the built in CameraViewController, the photo will be taken when I press the capture button, but it takes 2+ seconds or the camera screen to dismiss itself

**Comment by DavidSchechter** [comment]
Hi,
I tested a demo project on an iPhone 6 plus without changing any of the provided code and it does not take 2+ second to close.
We don't control the speed of built in animation from iOS.

When an image is taken this method is called:
public func imagePickerController(picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : AnyObject]) {
        var myImage = info[UIImagePickerControllerEditedImage] as? UIImage
        
        if myImage == nil {
            myImage = info[UIImagePickerControllerOriginalImage] as? UIImage
            /* Correctly flip the mirrored image of front-facing camera */
            if self.cameraDevice == UIImagePickerControllerCameraDevice.Front {
                if let im = myImage, cgImage = im.CGImage {
                    myImage = UIImage(CGImage: cgImage, scale: im.scale, orientation: UIImageOrientation.LeftMirrored)
                }
            }
        }
        
        if (cameraDelegate != nil) {
            cameraDelegate.pickedImage(myImage)
        }
    }

and immediately after:
    public func pickedImage(image: UIImage!) {
        self.cameraVC.dismissViewControllerAnimated(true, completion: nil)
        
        self.controller.sendImage(image,isIncomingMessage: false)
    }


As you can see, the camera controller is dismissed immediately after the image is taken.

Try testing on a different device, that could make it faster.

**Comment by stephensilber** [comment]
I've attached a video demo of what I'm talking about. dismissViewController does get called right away, but there seems to be some sort of delay for it actually dismissing. From what I can see, the main thread is not being blocked since the camera view is still a live preview.

Link:
http://up.silber.io/2W3M2Z3s1k14

**Comment by DavidSchechter** [comment]
Try making a demo project that has the same issue a share it here.
I saw in the video you have a "sendPicture" function, that could be causing your issue.
Like I said, in a bare bones project with no additions or alterations, this does not happen.

**Comment by stephensilber** [comment]
That `sendPicture` call is the same call that happens in the stock `NMessengerBarView`. All I do in there is create a cell:

```
let imageContent = NetworkImageContentNode(imageURL: imageUrl,
                                                       bubbleConfiguration: self.bubbleConfiguration)            
messageNode = FeedMessageNode(content: imageContent, feedItemId: feedItem.id)
```

and then call to my viewModel which runs code on a background thread. I'll work on a demo project that I can share here so that we can investigate more some time this week

**Comment by DavidSchechter** [comment]
Thanks.
Please also try running your project on different phone, if possible, to see if there's a change

**Comment by stephensilber** [comment]
I have tried on several devices, all with the same result unfortunately. Multiple iPhone 6 devices to be more specific
