### ISSUE TITLE
update AsyncDiplayKit version?

### ISSUE THREAD

**Issue by JustinM1** [eBay/NMessenger#43]
I'm using swift 3 and need to use the latest version of AsyncDisplayKit to compile without errors. I get this error when I try to install NMessenger: 

[!] Unable to satisfy the following requirements:

- `AsyncDisplayKit` required by `Podfile`
- `AsyncDisplayKit (= 1.9.90)` required by `Podfile.lock`
- `AsyncDisplayKit (= 1.9.80)` required by `NMessenger (1.0.2)`

Is there anything I can do to solve this issue or is it something you will need to update in a future version?

thanks

**Comment by Sundin** [comment]
Hi @JustinM1 !

I solved this by forking the NMessenger repo and changing the AsyncDisplayKit version specified at the very bottom of the NMessenger.podspec file to 1.9.90

**Comment by JustinM1** [comment]
Great, thanks Sundin. I normally just deal with cocoapods so I wasn't aware of this option. Hopefully the master gets updated soon to reflect the updated AsyncDisplayKit verision.

**Comment by atainter** [comment]
Are you seeing any issues with 1.9.90? When we updated from 1.9.80 to 1.9.81 we saw a bunch of performance related issues, so we switched back. We'll do our own testing, but it would be good to have another set of eyes.

**Comment by JustinM1** [comment]
To be honest, I'm just starting out with AsyncDisplayKit and messing around with it in a playground so I unfortunately cannot provide any feedback. I'm currently using JSQMessages but wanted to see if there were any noticeable performance changes using NMessenger. I'll check back regularly for updates and if I notice anything worth mentioning I'll let you know. NMessenger looks really cool and I look forward to checking it out.

Justin

**Comment by nguyenhuy** [comment]
@atainter: Let me know if you want to discuss performance issues after updating to a newer version. I have a bit of experience with both ASDK and messaging related stuffs. I wrote my own messaging app that uses JSQMessagesViewController and eventually implemented [AsyncMessagesViewController](https://github.com/nguyenhuy/AsyncMessagesViewController) on top of ASDK and Swift. I'm on the ASDK slack channel under "huy".

**Comment by atainter** [comment]
@nguyenhuy Cool! If you're more than welcome to contribute if that interests you. I think @DavidSchechter is working on swift 3 migration right now and also updating ASDK. We're not seeing the `1.9.81` issues we found earlier, so I think it was a temporary problem.

**Comment by DavidSchechter** [comment]
Fixed in #44
