### ISSUE TITLE
dismiss keyboard bug when scrolling down on tableNode - swift 3

### ISSUE THREAD

**Issue by JustinM1** [eBay/NMessenger#45]
When scrolling down on the tableView with the keyboard up the InputBarView does not stay in sync with the keyboard as it is being dismissed. I tried adding a few things around the scrollViewDidScroll if state.down == true and also in the KeyboardNotification to no avail. GIF below to show what I am talking about.

Also, just a heads up. The NMessengerViewController is rotating based on orientation. Just wanted to make you aware in case that was an unintended effect from updating the master. 

![keyboarddismissgif](https://cloud.githubusercontent.com/assets/18277828/18560865/6daa20fa-7b4b-11e6-91d5-63f26bfc3c10.gif)

**Comment by atainter** [comment]
I'm writing a functional test for orientation so that we can catch it next time. @DavidSchechter can you look into the inputbar issue?

**Comment by atainter** [comment]
@JustinM1 I just did some testing on my end. It looks like NMessengerViewController is **Not** rotating based on orientation for me. Did you override `shouldAutorotate`?

<img width="557" alt="screen shot 2016-09-15 at 11 47 27 am" src="https://cloud.githubusercontent.com/assets/7866859/18562932/87f88408-7b3a-11e6-89c6-6dbf6c55f9ea.png">

**Comment by atainter** [comment]
*Update:* did some more testing. It looks like app is launched in a landscape orientation, NMessenger starts and gets locked in the landscape mode.

**Comment by JustinM1** [comment]
Yea I didn't adjust anything relating to rotation and it was actually rotating before I even started looking at the source code. I've only been coding for 8months or else I'd try to be of more help in solving the problem. If there is anything I can do just let me know.

**Comment by JustinM1** [comment]
maybe this is the problem with rotation? 
Title: Configure ViewController rotation settings in Swift 3 on iOS 10 
https://forums.developer.apple.com/thread/62008

**Comment by atainter** [comment]
I've already fixed it in my PR (#46). Waiting for @DavidSchechter to merge it.

**Comment by atainter** [comment]
PR #46 merged

**Comment by DavidSchechter** [comment]
@JustinM1 regarding the keyboard issue:
I can't reproduce your issue.
What device is this happing on?
Are you imbedding NMessenger inside anything?
Can you make a demo project to show the problem?

**Comment by JustinM1** [comment]
@DavidSchechter  sorry for delay. I was looking into the issue some more and I believe what the issue was is that I also had IQKeyboardManager dependency in project. After removing it the issue was resolved. It seems that was causing the issue with the dismissing of the keyboard in certain situations. Thanks for following up.
