### ISSUE TITLE
Is it possible to add new message on top of the view?

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [eBay/NMessenger#47]
Hello, I want to implement something like pull to load more. What's the easiest way to do that?

**Comment by atainter** [comment]
https://github.com/eBay/NMessenger#head-prefetching

**Comment by mukyasa** [comment]
hey can u show some custom way when we can fetch the additional objects in main thread, Because it crashes when i put logic of adding new cells from coredata.Thanks
