### ISSUE TITLE
Text limitations

### ISSUE THREAD

**Issue by alexsanderkhitev** [eBay/NMessenger#50]
Hello! When I wrote three lines of text, the longer I could not get, how to get around this limitation?

**Comment by atainter** [comment]
I can add a property to set this limit. We limited the amount of input text so that users can't force a crash by posting a million line message.

**Comment by alexsanderkhitev** [comment]
Hello @atainter I understood but I think you can add a number of symbols, for example 100, 500 or 1000

**Comment by alexsanderkhitev** [comment]
@atainter I noticed that when the text box gets bigger (rises) posts remain in place, it is so?

**Comment by atainter** [comment]
You can limit by either, but we chose lines during development. There is actually already a property you can set on NMessengerBarView `open var numberOfRows:CGFloat = 3`
