### ISSUE TITLE
Xcode 8 with Swift 2.3

### ISSUE THREAD

**Issue by Denis1992** [eBay/NMessenger#55]
Hi,
I use Xcode 8 with swift 2.3. I have tried to install NMessenger (1.0.76) by pod.
So `AsyncDisplayKit (= 1.9.80)` required by `NMessenger (1.0.76)`. 
But xcode8 with Async 1.9.80 - https://github.com/facebook/AsyncDisplayKit/issues/2010
Any solutions?

**Comment by DavidSchechter** [comment]
Please use the latest version if NMessenger (1.0.77) with is using swift 3 and AsyncDisplayKit 1.9.90

**Comment by ignotusverum** [comment]
so no Swift 2.3 support ? :(

**Comment by yarodevuci** [comment]
@ignotusverum Just update it to the Xcode 8 with Swift 3 already 
If the library is written in pure swift 3 how you think it can support Swift 2.3?

**Comment by ignotusverum** [comment]
# For Swift 2.3 support
pod 'NMessenger', '1.0.76'

:)

**Comment by yarodevuci** [comment]
@ignotusverum 
I assume that is an old description that repo owners not have time to go and clean it up.
