### ISSUE TITLE
Can't use with Carthage

### ISSUE THREAD

**Issue by pdgwien** [eBay/NMessenger#56]
Hello,

when trying to use this package with Carthage, `carthage update` fails with the following error message:
```
*** Skipped building NMessenger due to the error:
Dependency "NMessenger" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/eBay/NMessenger/issues/new
```

The entry in the Cartfile is 
`github "eBay/nMessenger"`

Thanks!

**Comment by atainter** [comment]
@a-ono Submitted a PR for the carthage integration. @DavidSchechter and I don't have experience with Carthage.

**Comment by dodikk** [comment]
Still some Cocoapods related errors  https://github.com/eBay/NMessenger/issues/88
