### ISSUE TITLE
resizing avatar image?

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [eBay/NMessenger#58]
Hi, is there anyway to resize a 48px*48px avatar icon to 20*20? will ASImageNode cache network avatar images?

**Comment by atainter** [comment]
ASNetworkImageNode can download/cache images. You can use `preferredFrameSize` to resize the image. I believe I do that in the messageGroups example. https://github.com/eBay/NMessenger/blob/master/examples/MessageGroups/MessageGroups/ViewController.swift#L94

**Comment by jimmyzzzzzzz** [comment]
thanks. this works
