### ISSUE TITLE
StackedBubbles don't draw properly when bubble has multiple lines (plus quick fix)

### ISSUE THREAD

**Issue by potecuta** [eBay/NMessenger#60]
When you translated to swift 3 you wrote M_PI_2 instead of M_PI when defining a path causing the StackedBubbles to be drawn in a weird manner.

Just go to StackedBubbles.swift and in the sizeToBounds func  change the last addArc func call:

        path.addArc(center: CGPoint(x: rect.minX, y: rect.minY), radius: radius2, startAngle: CGFloat(M_PI_2), endAngle: CGFloat(-M_PI_2), clockwise: false)

to 

        path.addArc(center: CGPoint(x: rect.minX, y: rect.minY), radius: radius2, startAngle: CGFloat(M_PI), endAngle: CGFloat(-M_PI_2), clockwise: false)

**Comment by atainter** [comment]
Hi @protecuta. If you want to submit a PR for it, I'd be happy to merge it in. Otherwise, I can fix it.

**Comment by potecuta** [comment]
That was what I originally wanted to do, but I'm already fighting a deadline and every minute counts. I'm sorry that I can't do a pull request right now
