### ISSUE TITLE
memoryCache error 

### ISSUE THREAD

**Issue by pml2571** [eBay/NMessenger#64]
I run your demo after installing podfile. but it brings up an error as in the screenshot below.
Any ideas what the reason could be?
It's in ASPINRemoteImageDownloader.m
![screen shot 2016-11-05 at 10 49 31 pm](https://cloud.githubusercontent.com/assets/3819719/20035653/8f2431da-a3aa-11e6-95df-2e770ad5841b.png)

**Comment by Richard3332** [comment]
I got the same error. I hope someone can resolve this

**Comment by LouisBorlee** [comment]
Same error over here

**Comment by tobieplz** [comment]
Try adding pod ‘NMessenger’, '= 1.0.77'
pod ’AsyncDisplayKit’, '= 1.9.90'
pod 'PINRemoteImage', '= 3.0.0-beta.3'

**Comment by atainter** [comment]
#67

**Comment by atainter** [comment]
Updated in `1.0.79`
