### ISSUE TITLE
a better instruction how to start?

### ISSUE THREAD

**Issue by yarodevuci** [eBay/NMessenger#66]
I installed the pod to the fresh project
What are my next steps?
I could not use a new Nmessage VC or import anything
import NMessenger gives me an error. .. 
What I am doing wrong?

**Comment by atainter** [comment]
There is a known issue with AsyncDisplayKit's PinRemoteImage dependency. We're trying to find the problem.

**Comment by atainter** [comment]
#67

**Comment by dodikk** [comment]
Another issue on "better instructions"
https://github.com/eBay/NMessenger/issues/95
