### ISSUE TITLE
PinCache

### ISSUE THREAD

**Issue by imclean** [eBay/NMessenger#67]
Hi,

This won't even build now as missing PinCache prevents it.

**Comment by atainter** [comment]
Is this the example project or NMessenger?

**Comment by imclean** [comment]
Just cocoapod it into a clean project and build

**Comment by imclean** [comment]
Looks like a dependency in AsyncDisplaykit is going wrong

**Comment by atainter** [comment]
@DavidSchechter Do you have any knowledge about this. I know we just updated to ASDK 1.9.90

**Comment by atainter** [comment]
We could add PinRemoteImage as a dependency in our Podspec, but that's a bit of a hack.

**Comment by danieljmac** [comment]
Not sure if you guys saw this, but this might shed some light: https://github.com/facebook/AsyncDisplayKit/issues/2424 . Last comment says might be a problem again with 1.9.92.

**Comment by atainter** [comment]
Thanks for sharing. We did not see that. I'll update as soon as possible.

**Comment by atainter** [comment]
Probably Sunday morning unless @DavidSchechter can do it. I'm out of town without access to my computer.

**Comment by mbalex99** [comment]
Can we close this one now?

**Comment by danieljmac** [comment]
just a heads up via cocoapods... `pod 'NMessenger'` in a fresh project still wont build with the missing pincache error. But `pod 'NMessenger', :git => 'https://github.com/eBay/NMessenger.git', :branch => 'master', :submodules => true` seems to pod install & build successfully

**Comment by atainter** [comment]
Yes, I haven't updated the pod yet. I'll close once I've updated the version.

**Comment by danieljmac** [comment]
Also, thanks for creating+maintaining this 👍  Looks really cool & I'm excited to dig in :)

**Comment by Richard3332** [comment]
Cool when will it be updated? :D

**Comment by atainter** [comment]
Should be updated now `1.0.79`.
