### ISSUE TITLE
NMessengerViewController Memory Leak.

### ISSUE THREAD

**Issue by FlorianPraile** [eBay/NMessenger#68]
When subclassing NMessengerViewController, without any other code than the deinit function. When the View controller is pushed from root view controller in a navigation, on pop back deinit is never called. I've made the test by replacing the extend of NMessengerViewController by UIViewController, the deinit was called.

So I've check the code and found some problems with delegate attributes

> `open class NMessenger: UIView { `
&nbsp; &nbsp;  `// ...` 
 &nbsp; &nbsp;  ` open `  **weak** ` var delegate: NMessengerDelegate?`
&nbsp; &nbsp;  `// ...` 
`}` 

>`open class CameraViewController {`
&nbsp; &nbsp;   `open `**weak**` var cameraDelegate: CameraViewDelegate!`
`}` 
`public protocol CameraViewDelegate`**: class**`{`

>`open class InputBarView: UIView, InputBarViewProtocol {`
&nbsp; &nbsp;   `open `**weak**` controller:NMessengerViewController!`
`}` 

 I've found  these missing weak, but I'm still missing some of them or it is another stuff, because deinit is still not called. Usually in the cocoa framework we have to set delegate as weak, and not to keep a strong reference to them if they need to be deinit https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/Delegation.html

**Edit**
I think I've found one more in 
> `open class GeneralMessengerCell: ASCellNode { `
&nbsp; &nbsp;  `// ...` 
 &nbsp; &nbsp;  ` open `  **weak** ` var currentViewController: UIViewController?`
&nbsp; &nbsp;  `// ...` 
`}` 

But it still not deinit.

**Comment by atainter** [comment]
Hi, thanks for bringing this up. This messenger was the root view controller of the app we developed for this project, so it didn't really cross my mind to do this. I believe there are quite a few strong references in NMessenger, so it needs some refactoring. I'll try to work on it when I get time, but I'm not sure how long it will take since I am wrapped up with a few other things.
