### ISSUE TITLE
Issue with Input bar.

### ISSUE THREAD

**Issue by MacMeDan** [eBay/NMessenger#7]
Provided is a screen shot of what I am seeing. 
-Device Description
>> iphone6+ 
>> running iOS9.3

I do have Gboard installed I don't know if that is the root of the issue or not.

-Issue Description
The input bar is floating way above the top of the keyboard.
![ScreenShot](https://cloud.githubusercontent.com/assets/6182351/17754226/be9606ea-6490-11e6-98c2-4cc9018d1763.jpg)

When swapping keyboards the input field is now gone. I would assume it is under the keyboard.
if I quit the app and and relaunch with regular keyboard it seems to be fine. Then switching to Gboard the input feild launches up and disappears once you swap back again. Also all messages are gone after this point.

**Comment by MacMeDan** [comment]
I also had to disable bitcode to get it to work.

**Comment by MacMeDan** [comment]
Here is a video of it. Had to compress it because of githubs size constraints.

[keybaordbugC.zip](https://github.com/eBay/NMessenger/files/423693/keybaordbugC.zip)

**Comment by DavidSchechter** [comment]
Is this happening on the simulator or on a device?

**Comment by MacMeDan** [comment]
Real device.

**Comment by MacMeDan** [comment]
It seems very related to the third party keyboard.

**Comment by MacMeDan** [comment]
Just ran it on the simulator iPadPro and same issue but no 3rd Party keyboard just swapping to the emoji keyboard.

**Comment by MacMeDan** [comment]
![simulator screen shot aug 17 2016 4 00 28 pm](https://cloud.githubusercontent.com/assets/6182351/17754834/b9cde940-6493-11e6-99a8-696c4f77d828.png)

**Comment by MacMeDan** [comment]
Also when you dismiss the keyboard the send button is disabled even when there is content in the text field.

**Comment by MacMeDan** [comment]
The iPhone6 simulator did not seem to have the same result.

**Comment by MacMeDan** [comment]
Also if you rotate everything breaks.

**Comment by MacMeDan** [comment]
Rotation does quite a number on everything actually.  This is the state of things after 
1. rotating to landscape
2. rotating to portrait
3. back to landscape 
4. grab the input bar of top of screen and pull down to hide keyboard 
5. then back to portrait so your messages show again.

![img_0011](https://cloud.githubusercontent.com/assets/6182351/17755050/fbc49f8c-6494-11e6-9983-52bd36da4a1d.jpg)

**Comment by DavidSchechter** [comment]
#8 fixed in this PR

**Comment by atainter** [comment]
Merged
