### ISSUE TITLE
Show timestamp every 3rd message

### ISSUE THREAD

**Issue by yarodevuci** [eBay/NMessenger#75]
I find `[MessageGroup]()` a little bit confusing. How can I show a timestamp every 3rd row?

**Comment by atainter** [comment]
Write some logic that creates a new message group for every 3 messages.

**Comment by yarodevuci** [comment]
@atainter There is no way to use indexpath or something in collectionview?

**Comment by atainter** [comment]
NMessenger does not use the typical data for indexpath model.
