### ISSUE TITLE
NMessenger bakcground color

### ISSUE THREAD

**Issue by yarodevuci** [eBay/NMessenger#80]
How to change chat background color ? 
I tried:   
    ` self.messengerView.backgroundColor = .black`
`      self.messengerView.messengerNode.backgroundColor = .black
`

But nothing changed. Any other ways?

**Comment by yarodevuci** [comment]
Got it
`        self.messengerView.messengerNode.backgroundColor = .black
`

**Comment by Sundin** [comment]
Try this:

`self.messengerView.messengerNode?.view.backgroundColor = .black`

**Comment by JordanRoPo** [comment]
i've tried all three of these and the problem i'm still facing is that the background color for each individual node is still white

**Comment by johnnyoin** [comment]
@JordanRoPo You can use bubbleConfiguration, for example:
```Swift
let textContent = TextContentNode(textMessageString: text, bubbleConfiguration: MyBubbleConfiguration())
let newMessage = MessageNode(content: textContent)
```
