### ISSUE TITLE
input bar offset.

### ISSUE THREAD

**Issue by MacMeDan** [eBay/NMessenger#9]
Provided is a screen shot of what I am seeing. 
-Device Description
>> iphone6+ 
>> running iOS9.3

-Issue Description
>>> My previous issue was closed but it seems to not be resolved. I have pulled the latest master and ran a pod update but when i run the example and switch keyboards the input field is way above the keyboard.
I do have Gboard installed but the issue is replicated also by switching back and forth from the emoji keyboard.

![ScreenShot](https://cloud.githubusercontent.com/assets/6182351/17754226/be9606ea-6490-11e6-98c2-4cc9018d1763.jpg)

When swapping keyboards the input field is now gone. I would assume it is under the keyboard.
if I quit the app and and relaunch with regular keyboard it seems to be fine. Then switching to Gboard the input feild launches up and disappears once you swap back again. Also all messages are gone after this point.

**Comment by DavidSchechter** [comment]
I don't understand - are you using the latest code from master or just did pod update?

**Comment by MacMeDan** [comment]
Both I pulled the latest code from master saw no change and pod updated and still saw no change.

**Comment by DavidSchechter** [comment]
pod 'NMessenger', :git => 'https://github.com/eBay/NMessenger.git', :commit => 'b562432'

**Comment by MacMeDan** [comment]
ok will do

**Comment by DavidSchechter** [comment]
Or try this to always get the latest from master

pod 'NMessenger', :git => ''https://github.com/eBay/NMessenger.git'

**Comment by MacMeDan** [comment]
Wait @DavidSchechter isn't  `NMessager` the target.

**Comment by DavidSchechter** [comment]
When you do pod 'NMessenger' with out a git or commit it get the latest version from cocoapods.
If you use :git it will get the latest version from github.
If you use :commit it will get a specific commit from github.

Read more here - https://guides.cocoapods.org/using/the-podfile.html

**Comment by MacMeDan** [comment]
No I understand what you are saying there. My confusion is with this line. 

>> pod 'NMessenger', :git => ''https://github.com/eBay/NMessenger.git'

do you want me to add that to the `Podfile` of the `nMessanger` project because that seems like a reference to itself. That is why I am confused. So the `Podfile` would looke like this 

>>platform :ios, '9.0'
>>use_frameworks!

>>target 'nMessenger' do
>># For latest release in cocoapods
>>pod 'NMessenger', :git => ''https://github.com/eBay/NMessenger.git"
>>pod 'AsyncDisplayKit', '1.9.80'
>>end

Is that what you are saying?

**Comment by DavidSchechter** [comment]
No
In your own project's pod file you should only have this line:

**Comment by MacMeDan** [comment]
Ok that is what I thought.
Ya all these issues are on your `nMessenger` Project

**Comment by DavidSchechter** [comment]
nMessenger is not a demo project

**Comment by MacMeDan** [comment]
lol. Ok then I will stop trying to report issues on it. 😀 Ill let you know if I see it on my own implementation.

**Comment by DavidSchechter** [comment]
nMessenger project it to work on nMessenger and fix bug and add features. There is an examples folder for demo projects.

**Comment by MacMeDan** [comment]
sweet I will check them out. Thanks @DavidSchechter and awesome work also. 👍🏼
