### ISSUE TITLE
Hide NMessengerViewController inputBarView

### ISSUE THREAD

**Issue by AndreMarvell** [eBay/NMessenger#99]
First of all, thank you for this awesome library.

Is it possible to hide NMessengerViewController inputBarview ?
Because i simply tried 
``` swift
self.inputBarView.isHidden = true
``` 
But it's not working.

**Comment by AndreMarvell** [comment]
This ticket can be closed. I've found a solution, i simply disabled the left button, right button and the texview when the chat is closed.

**Comment by ashleykrose** [comment]
I'm having this issue. I can hide the input bar but there is still a white space. I can't figure out how you disabled those things to get the white bar to disappear as well. Any help is greatly appreciated.
<img width="287" alt="screen shot 2017-08-02 at 2 58 41 pm" src="https://user-images.githubusercontent.com/8593303/28889773-1ebbd5c0-7793-11e7-8d4e-792e7138c4e3.png">
<img width="284" alt="screen shot 2017-08-02 at 2 57 38 pm" src="https://user-images.githubusercontent.com/8593303/28889774-1ebc4bcc-7793-11e7-9d5c-0f87515d70a0.png">
